// Generated by scripts/generate-builtin-table-styles.mjs. Do not edit by hand.
//
// Excel's built-in table styles (TableStyleLight1-21, TableStyleMedium1-28 and
// TableStyleDark1-11) as defined in ECMA-376 Part 1, taken from Apache POI's
// presetTableStyles.xml. Workbooks only reference these styles by name, so the
// viewer ships the definitions. Element values use the same shape that
// parseDifferentialStyle produces for custom table styles in styles.xml.
//
// Regenerate with: node scripts/generate-builtin-table-styles.mjs
import type { XlsxTableStyleDefinition } from "./types";

export const BUILTIN_TABLE_STYLES: Record<string, XlsxTableStyleDefinition> = {
  TableStyleLight1: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "thin"}, "bottom": {"color": {"theme": 1}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"bottom": {"color": {"theme": 1}, "style": "thin"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "thin"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleLight2: {
    wholeTable: {"font": {"color": {"theme": 4, "tint": -0.25}}, "border": {"top": {"color": {"theme": 4}, "style": "thin"}, "bottom": {"color": {"theme": 4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 4, "tint": -0.25}}, "border": {"bottom": {"color": {"theme": 4}, "style": "thin"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 4, "tint": -0.25}}, "border": {"top": {"color": {"theme": 4}, "style": "thin"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 4, "tint": -0.25}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 4, "tint": -0.25}}},
    firstRowStripe: {"fill": {"color": {"theme": 4, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 4, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight3: {
    wholeTable: {"font": {"color": {"theme": 5, "tint": -0.25}}, "border": {"top": {"color": {"theme": 5}, "style": "thin"}, "bottom": {"color": {"theme": 5}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 5, "tint": -0.25}}, "border": {"bottom": {"color": {"theme": 5}, "style": "thin"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 5, "tint": -0.25}}, "border": {"top": {"color": {"theme": 5}, "style": "thin"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 5, "tint": -0.25}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 5, "tint": -0.25}}},
    firstRowStripe: {"fill": {"color": {"theme": 5, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 5, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight4: {
    wholeTable: {"font": {"color": {"theme": 6, "tint": -0.25}}, "border": {"top": {"color": {"theme": 6}, "style": "thin"}, "bottom": {"color": {"theme": 6}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 6, "tint": -0.25}}, "border": {"bottom": {"color": {"theme": 6}, "style": "thin"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 6, "tint": -0.25}}, "border": {"top": {"color": {"theme": 6}, "style": "thin"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 6, "tint": -0.25}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 6, "tint": -0.25}}},
    firstRowStripe: {"fill": {"color": {"theme": 6, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 6, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight5: {
    wholeTable: {"font": {"color": {"theme": 7, "tint": -0.25}}, "border": {"top": {"color": {"theme": 7}, "style": "thin"}, "bottom": {"color": {"theme": 7}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 7, "tint": -0.25}}, "border": {"bottom": {"color": {"theme": 7}, "style": "thin"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 7, "tint": -0.25}}, "border": {"top": {"color": {"theme": 7}, "style": "thin"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 7, "tint": -0.25}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 7, "tint": -0.25}}},
    firstRowStripe: {"fill": {"color": {"theme": 7, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 7, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight6: {
    wholeTable: {"font": {"color": {"theme": 8, "tint": -0.25}}, "border": {"top": {"color": {"theme": 8}, "style": "thin"}, "bottom": {"color": {"theme": 8}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 8, "tint": -0.25}}, "border": {"bottom": {"color": {"theme": 8}, "style": "thin"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 8, "tint": -0.25}}, "border": {"top": {"color": {"theme": 8}, "style": "thin"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 8, "tint": -0.25}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 8, "tint": -0.25}}},
    firstRowStripe: {"fill": {"color": {"theme": 8, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 8, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight7: {
    wholeTable: {"font": {"color": {"theme": 9, "tint": -0.25}}, "border": {"top": {"color": {"theme": 9}, "style": "thin"}, "bottom": {"color": {"theme": 9}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 9, "tint": -0.25}}, "border": {"bottom": {"color": {"theme": 9}, "style": "thin"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 9, "tint": -0.25}}, "border": {"top": {"color": {"theme": 9}, "style": "thin"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 9, "tint": -0.25}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 9, "tint": -0.25}}},
    firstRowStripe: {"fill": {"color": {"theme": 9, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 9, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight8: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "thin"}, "right": {"color": {"theme": 1}, "style": "thin"}, "bottom": {"color": {"theme": 1}, "style": "thin"}, "left": {"color": {"theme": 1}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"border": {"top": {"color": {"theme": 1}, "style": "thin"}}},
    secondRowStripe: {"border": {"top": {"color": {"theme": 1}, "style": "thin"}}},
    firstColumnStripe: {"border": {"left": {"color": {"theme": 1}, "style": "thin"}}},
    secondColumnStripe: {"border": {"left": {"color": {"theme": 1}, "style": "thin"}}}
  },
  TableStyleLight9: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 4}, "style": "thin"}, "right": {"color": {"theme": 4}, "style": "thin"}, "bottom": {"color": {"theme": 4}, "style": "thin"}, "left": {"color": {"theme": 4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 4}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"border": {"top": {"color": {"theme": 4}, "style": "thin"}}},
    secondRowStripe: {"border": {"top": {"color": {"theme": 4}, "style": "thin"}}},
    firstColumnStripe: {"border": {"left": {"color": {"theme": 4}, "style": "thin"}}},
    secondColumnStripe: {"border": {"left": {"color": {"theme": 4}, "style": "thin"}}}
  },
  TableStyleLight10: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 5}, "style": "thin"}, "right": {"color": {"theme": 5}, "style": "thin"}, "bottom": {"color": {"theme": 5}, "style": "thin"}, "left": {"color": {"theme": 5}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 5}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"border": {"top": {"color": {"theme": 5}, "style": "thin"}}},
    secondRowStripe: {"border": {"top": {"color": {"theme": 5}, "style": "thin"}}},
    firstColumnStripe: {"border": {"left": {"color": {"theme": 5}, "style": "thin"}}},
    secondColumnStripe: {"border": {"left": {"color": {"theme": 5}, "style": "thin"}}}
  },
  TableStyleLight11: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 6}, "style": "thin"}, "right": {"color": {"theme": 6}, "style": "thin"}, "bottom": {"color": {"theme": 6}, "style": "thin"}, "left": {"color": {"theme": 6}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 6}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"border": {"top": {"color": {"theme": 6}, "style": "thin"}}},
    secondRowStripe: {"border": {"top": {"color": {"theme": 6}, "style": "thin"}}},
    firstColumnStripe: {"border": {"left": {"color": {"theme": 6}, "style": "thin"}}},
    secondColumnStripe: {"border": {"left": {"color": {"theme": 6}, "style": "thin"}}}
  },
  TableStyleLight12: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 7}, "style": "thin"}, "right": {"color": {"theme": 7}, "style": "thin"}, "bottom": {"color": {"theme": 7}, "style": "thin"}, "left": {"color": {"theme": 7}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 7}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"border": {"top": {"color": {"theme": 7}, "style": "thin"}}},
    secondRowStripe: {"border": {"top": {"color": {"theme": 7}, "style": "thin"}}},
    firstColumnStripe: {"border": {"left": {"color": {"theme": 7}, "style": "thin"}}},
    secondColumnStripe: {"border": {"left": {"color": {"theme": 7}, "style": "thin"}}}
  },
  TableStyleLight13: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 8}, "style": "thin"}, "right": {"color": {"theme": 8}, "style": "thin"}, "bottom": {"color": {"theme": 8}, "style": "thin"}, "left": {"color": {"theme": 8}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 8}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"border": {"top": {"color": {"theme": 8}, "style": "thin"}}},
    secondRowStripe: {"border": {"top": {"color": {"theme": 8}, "style": "thin"}}},
    firstColumnStripe: {"border": {"left": {"color": {"theme": 8}, "style": "thin"}}},
    secondColumnStripe: {"border": {"left": {"color": {"theme": 8}, "style": "thin"}}}
  },
  TableStyleLight14: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 9}, "style": "thin"}, "right": {"color": {"theme": 9}, "style": "thin"}, "bottom": {"color": {"theme": 9}, "style": "thin"}, "left": {"color": {"theme": 9}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 9}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"border": {"top": {"color": {"theme": 9}, "style": "thin"}}},
    secondRowStripe: {"border": {"top": {"color": {"theme": 9}, "style": "thin"}}},
    firstColumnStripe: {"border": {"left": {"color": {"theme": 9}, "style": "thin"}}},
    secondColumnStripe: {"border": {"left": {"color": {"theme": 9}, "style": "thin"}}}
  },
  TableStyleLight15: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "thin"}, "right": {"color": {"theme": 1}, "style": "thin"}, "bottom": {"color": {"theme": 1}, "style": "thin"}, "left": {"color": {"theme": 1}, "style": "thin"}, "horizontal": {"color": {"theme": 1}, "style": "thin"}, "vertical": {"color": {"theme": 1}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"bottom": {"color": {"theme": 1}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleLight16: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 4}, "style": "thin"}, "right": {"color": {"theme": 4}, "style": "thin"}, "bottom": {"color": {"theme": 4}, "style": "thin"}, "left": {"color": {"theme": 4}, "style": "thin"}, "horizontal": {"color": {"theme": 4}, "style": "thin"}, "vertical": {"color": {"theme": 4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"bottom": {"color": {"theme": 4}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 4}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 4, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 4, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight17: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 5}, "style": "thin"}, "right": {"color": {"theme": 5}, "style": "thin"}, "bottom": {"color": {"theme": 5}, "style": "thin"}, "left": {"color": {"theme": 5}, "style": "thin"}, "horizontal": {"color": {"theme": 5}, "style": "thin"}, "vertical": {"color": {"theme": 5}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"bottom": {"color": {"theme": 5}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 5}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 5, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 5, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight18: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 6}, "style": "thin"}, "right": {"color": {"theme": 6}, "style": "thin"}, "bottom": {"color": {"theme": 6}, "style": "thin"}, "left": {"color": {"theme": 6}, "style": "thin"}, "horizontal": {"color": {"theme": 6}, "style": "thin"}, "vertical": {"color": {"theme": 6}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"bottom": {"color": {"theme": 6}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 6}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 6, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 6, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight19: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 7}, "style": "thin"}, "right": {"color": {"theme": 7}, "style": "thin"}, "bottom": {"color": {"theme": 7}, "style": "thin"}, "left": {"color": {"theme": 7}, "style": "thin"}, "horizontal": {"color": {"theme": 7}, "style": "thin"}, "vertical": {"color": {"theme": 7}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"bottom": {"color": {"theme": 7}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 7}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 7, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 7, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight20: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 8}, "style": "thin"}, "right": {"color": {"theme": 8}, "style": "thin"}, "bottom": {"color": {"theme": 8}, "style": "thin"}, "left": {"color": {"theme": 8}, "style": "thin"}, "horizontal": {"color": {"theme": 8}, "style": "thin"}, "vertical": {"color": {"theme": 8}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"bottom": {"color": {"theme": 8}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 8}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 8, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 8, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleLight21: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 9}, "style": "thin"}, "right": {"color": {"theme": 9}, "style": "thin"}, "bottom": {"color": {"theme": 9}, "style": "thin"}, "left": {"color": {"theme": 9}, "style": "thin"}, "horizontal": {"color": {"theme": 9}, "style": "thin"}, "vertical": {"color": {"theme": 9}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"bottom": {"color": {"theme": 9}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 9}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 9, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 9, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleMedium1: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "thin"}, "right": {"color": {"theme": 1}, "style": "thin"}, "bottom": {"color": {"theme": 1}, "style": "thin"}, "left": {"color": {"theme": 1}, "style": "thin"}, "horizontal": {"color": {"theme": 1}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleMedium2: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 4}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 4, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 4, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleMedium3: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 5}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 5, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 5, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleMedium4: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 6}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 6, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 6, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleMedium5: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 7}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 7, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 7, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleMedium6: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 8}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 8, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 8, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleMedium7: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 9}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 9, "tint": 0.8}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 9, "tint": 0.8}, "fillType": "solid"}}
  },
  TableStyleMedium8: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}, "border": {"horizontal": {"color": {"theme": 0}, "style": "thin"}, "vertical": {"color": {"theme": 0}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "thick"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "thick"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.35}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.35}, "fillType": "solid"}}
  },
  TableStyleMedium9: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 4, "tint": 0.8}, "fillType": "solid"}, "border": {"horizontal": {"color": {"theme": 0}, "style": "thin"}, "vertical": {"color": {"theme": 0}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "thick"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "thick"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 4, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 4, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium10: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 5, "tint": 0.8}, "fillType": "solid"}, "border": {"horizontal": {"color": {"theme": 0}, "style": "thin"}, "vertical": {"color": {"theme": 0}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "thick"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "thick"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 5, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 5, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium11: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 6, "tint": 0.8}, "fillType": "solid"}, "border": {"horizontal": {"color": {"theme": 0}, "style": "thin"}, "vertical": {"color": {"theme": 0}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "thick"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "thick"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 6, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 6, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium12: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 7, "tint": 0.8}, "fillType": "solid"}, "border": {"horizontal": {"color": {"theme": 0}, "style": "thin"}, "vertical": {"color": {"theme": 0}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "thick"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "thick"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 7, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 7, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium13: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 8, "tint": 0.8}, "fillType": "solid"}, "border": {"horizontal": {"color": {"theme": 0}, "style": "thin"}, "vertical": {"color": {"theme": 0}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "thick"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "thick"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 8, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 8, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium14: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 9, "tint": 0.8}, "fillType": "solid"}, "border": {"horizontal": {"color": {"theme": 0}, "style": "thin"}, "vertical": {"color": {"theme": 0}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "thick"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "thick"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 9, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 9, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium15: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "medium"}, "right": {"color": {"theme": 1}, "style": "thin"}, "bottom": {"color": {"theme": 1}, "style": "medium"}, "left": {"color": {"theme": 1}, "style": "thin"}, "horizontal": {"color": {"theme": 1}, "style": "thin"}, "vertical": {"color": {"theme": 1}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 1}, "style": "medium"}}},
    totalRow: {"border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleMedium16: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "medium"}, "bottom": {"color": {"theme": 1}, "style": "medium"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 1}, "style": "medium"}}},
    totalRow: {"border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleMedium17: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "medium"}, "bottom": {"color": {"theme": 1}, "style": "medium"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 1}, "style": "medium"}}},
    totalRow: {"border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleMedium18: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "medium"}, "bottom": {"color": {"theme": 1}, "style": "medium"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 1}, "style": "medium"}}},
    totalRow: {"border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleMedium19: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "medium"}, "bottom": {"color": {"theme": 1}, "style": "medium"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 1}, "style": "medium"}}},
    totalRow: {"border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleMedium20: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "medium"}, "bottom": {"color": {"theme": 1}, "style": "medium"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 1}, "style": "medium"}}},
    totalRow: {"border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleMedium21: {
    wholeTable: {"font": {"color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "medium"}, "bottom": {"color": {"theme": 1}, "style": "medium"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 1}, "style": "medium"}}},
    totalRow: {"border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}}
  },
  TableStyleMedium22: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 1}, "style": "thin"}, "right": {"color": {"theme": 1}, "style": "thin"}, "bottom": {"color": {"theme": 1}, "style": "thin"}, "left": {"color": {"theme": 1}, "style": "thin"}, "horizontal": {"color": {"theme": 1}, "style": "thin"}, "vertical": {"color": {"theme": 1}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.35}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.35}, "fillType": "solid"}}
  },
  TableStyleMedium23: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 4, "tint": 0.8}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}, "vertical": {"color": {"theme": 4, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 4}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 4, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 4, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium24: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 5, "tint": 0.8}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}, "vertical": {"color": {"theme": 5, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 5}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 5, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 5, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium25: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 6, "tint": 0.8}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}, "vertical": {"color": {"theme": 6, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 6}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 6, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 6, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium26: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 7, "tint": 0.8}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}, "vertical": {"color": {"theme": 7, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 7}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 7, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 7, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium27: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 8, "tint": 0.8}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}, "vertical": {"color": {"theme": 8, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 8}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 8, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 8, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleMedium28: {
    wholeTable: {"font": {"color": {"theme": 1}}, "fill": {"color": {"theme": 9, "tint": 0.8}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}, "right": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}, "bottom": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}, "left": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}, "horizontal": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}, "vertical": {"color": {"theme": 9, "tint": 0.4}, "style": "thin"}}},
    headerRow: {"font": {"bold": true, "color": {"theme": 1}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 9}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 9, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 9, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleDark1: {
    wholeTable: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 1, "tint": 0.45}, "fillType": "solid"}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1, "tint": 0.15}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1, "tint": 0.25}, "fillType": "solid"}, "border": {"right": {"color": {"theme": 0}, "style": "medium"}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1, "tint": 0.25}, "fillType": "solid"}, "border": {"left": {"color": {"theme": 0}, "style": "medium"}}},
    firstRowStripe: {"fill": {"color": {"theme": 1, "tint": 0.25}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 1, "tint": 0.25}, "fillType": "solid"}}
  },
  TableStyleDark2: {
    wholeTable: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 4}, "fillType": "solid"}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4, "tint": -0.5}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4, "tint": -0.25}, "fillType": "solid"}, "border": {"right": {"color": {"theme": 0}, "style": "medium"}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 4, "tint": -0.25}, "fillType": "solid"}, "border": {"left": {"color": {"theme": 0}, "style": "medium"}}},
    firstRowStripe: {"fill": {"color": {"theme": 4, "tint": -0.25}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 4, "tint": -0.25}, "fillType": "solid"}}
  },
  TableStyleDark3: {
    wholeTable: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5, "tint": -0.5}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5, "tint": -0.25}, "fillType": "solid"}, "border": {"right": {"color": {"theme": 0}, "style": "medium"}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 5, "tint": -0.25}, "fillType": "solid"}, "border": {"left": {"color": {"theme": 0}, "style": "medium"}}},
    firstRowStripe: {"fill": {"color": {"theme": 5, "tint": -0.25}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 5, "tint": -0.25}, "fillType": "solid"}}
  },
  TableStyleDark4: {
    wholeTable: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 6}, "fillType": "solid"}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6, "tint": -0.5}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6, "tint": -0.25}, "fillType": "solid"}, "border": {"right": {"color": {"theme": 0}, "style": "medium"}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 6, "tint": -0.25}, "fillType": "solid"}, "border": {"left": {"color": {"theme": 0}, "style": "medium"}}},
    firstRowStripe: {"fill": {"color": {"theme": 6, "tint": -0.25}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 6, "tint": -0.25}, "fillType": "solid"}}
  },
  TableStyleDark5: {
    wholeTable: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7, "tint": -0.5}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7, "tint": -0.25}, "fillType": "solid"}, "border": {"right": {"color": {"theme": 0}, "style": "medium"}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 7, "tint": -0.25}, "fillType": "solid"}, "border": {"left": {"color": {"theme": 0}, "style": "medium"}}},
    firstRowStripe: {"fill": {"color": {"theme": 7, "tint": -0.25}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 7, "tint": -0.25}, "fillType": "solid"}}
  },
  TableStyleDark6: {
    wholeTable: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 8}, "fillType": "solid"}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8, "tint": -0.5}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8, "tint": -0.25}, "fillType": "solid"}, "border": {"right": {"color": {"theme": 0}, "style": "medium"}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 8, "tint": -0.25}, "fillType": "solid"}, "border": {"left": {"color": {"theme": 0}, "style": "medium"}}},
    firstRowStripe: {"fill": {"color": {"theme": 8, "tint": -0.25}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 8, "tint": -0.25}, "fillType": "solid"}}
  },
  TableStyleDark7: {
    wholeTable: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}},
    headerRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}, "border": {"bottom": {"color": {"theme": 0}, "style": "medium"}}},
    totalRow: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9, "tint": -0.5}, "fillType": "solid"}, "border": {"top": {"color": {"theme": 0}, "style": "medium"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9, "tint": -0.25}, "fillType": "solid"}, "border": {"right": {"color": {"theme": 0}, "style": "medium"}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 0}}, "fill": {"color": {"theme": 9, "tint": -0.25}, "fillType": "solid"}, "border": {"left": {"color": {"theme": 0}, "style": "medium"}}},
    firstRowStripe: {"fill": {"color": {"theme": 9, "tint": -0.25}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 9, "tint": -0.25}, "fillType": "solid"}}
  },
  TableStyleDark8: {
    wholeTable: {"fill": {"color": {"theme": 0, "tint": -0.15}, "fillType": "solid"}},
    headerRow: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 1}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 0, "tint": -0.35}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 0, "tint": -0.35}, "fillType": "solid"}}
  },
  TableStyleDark9: {
    wholeTable: {"fill": {"color": {"theme": 4, "tint": 0.8}, "fillType": "solid"}},
    headerRow: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 5}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 4, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 4, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleDark10: {
    wholeTable: {"fill": {"color": {"theme": 6, "tint": 0.8}, "fillType": "solid"}},
    headerRow: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 7}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 6, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 6, "tint": 0.6}, "fillType": "solid"}}
  },
  TableStyleDark11: {
    wholeTable: {"fill": {"color": {"theme": 8, "tint": 0.8}, "fillType": "solid"}},
    headerRow: {"font": {"color": {"theme": 0}}, "fill": {"color": {"theme": 9}, "fillType": "solid"}},
    totalRow: {"font": {"bold": true, "color": {"theme": 1}}, "border": {"top": {"color": {"theme": 1}, "style": "double"}}},
    firstColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    lastColumn: {"font": {"bold": true, "color": {"theme": 1}}},
    firstRowStripe: {"fill": {"color": {"theme": 8, "tint": 0.6}, "fillType": "solid"}},
    firstColumnStripe: {"fill": {"color": {"theme": 8, "tint": 0.6}, "fillType": "solid"}}
  }
};

/**
 * Resolves one of Excel's built-in table styles by name. Workbooks reference
 * these by name only, so the definitions ship with the viewer. Returns null for
 * any other name, including custom styles defined in the workbook's styles.xml.
 */
export function resolveBuiltinTableStyle(name: string | undefined): XlsxTableStyleDefinition | null {
  if (!name || !Object.prototype.hasOwnProperty.call(BUILTIN_TABLE_STYLES, name)) {
    return null;
  }

  return BUILTIN_TABLE_STYLES[name] ?? null;
}
